version: '3.3'

services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:latest
    container_name: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api=true"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.teamspeak.address=:9987/udp"
      - "--entrypoints.teamspeak_serverquery_raw.address=:10011"
      - "--entrypoints.teamspeak_serverquery_ssh.address=:10022"
      - "--entrypoints.teamspeak_filetransfer.address=:30033"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email={YOUR_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.mytlschallenge.acme.keytype=EC384"
      - "--certificatesresolvers.mytlschallenge.acme.preferredchain='ISRG Root X1'"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "443:443"
      # TODO ts3 - test -
      - "9987:9987/udp"
      - "10011:10011"
      - "10022:10022"
      - "30033:30033"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/traefik/userfile:/userfile:ro"
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=dashboardauth"
      # for manuall installation unquote this:
      # "traefik.http.middlewares.dashboardauth.basicauth.users=${DASHBOARD_USER_PASS}"
      - "traefik.http.middlewares.dashboardauth.basicauth.usersfile=/userfile"
        # Global redirection: http to https
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:(www.)?.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=wwwtohttps"
      # Global redirection: https (www.) to https
      - "traefik.http.routers.wwwsecure-catchall.rule=HostRegexp(`{host:(www.).+}`)"
      - "traefik.http.routers.wwwsecure-catchall.entrypoints=websecure"
      - "traefik.http.routers.wwwsecure-catchall.tls=true"
      - "traefik.http.routers.wwwsecure-catchall.middlewares=wwwtohttps"
      # middleware: http(s)://(www.) to  https://
      - "traefik.http.middlewares.wwwtohttps.redirectregex.regex=^https?://(?:www.)?(.+)"
      - "traefik.http.middlewares.wwwtohttps.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.wwwtohttps.redirectregex.permanent=true"
      # TODO ts3 - test -
      - "traefik.udp.routers.my-router.entrypoints=udp"
    networks:
      - proxy
networks:
  proxy:
    external: true