version: "3.3"

services:
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    container_name: "gitlab"
    restart: unless-stopped
    ports:
      - "30022:22"
    environment:
      GITLAB_SHELL_SSH_PORT: 30022
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.${DOMAIN}'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        nginx['proxy_set_headers'] = {
          'X-Forwarded-Proto' => 'https',
          'X-Forwarded-Ssl' => 'on'
        }
        gitlab_rails['initial_root_password'] = "${ROOT_PASSWORD}"
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.${DOMAIN}"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "gitlab@${DOMAIN}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${DOMAIN}"
        gitlab_rails['smtp_authentication'] = "plain"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['manage_backup_path'] = true
        gitlab_rails['backup_path'] = "/var/opt/gitlab/backups"
        gitlab_rails['backup_upload_remote_directory'] = '${AWS_UPLOAD_REMOTE_DIR}'
        gitlab_rails['backup_upload_connection'] = {
           'provider' => 'AWS',
           'region' => '${AWS_REGION}',
           'aws_access_key_id' => '${AWS_ACCESS_KEY_ID}',
           'aws_secret_access_key' => '${AWS_SECRET_ACCESS_KEY}',
           # # If IAM profile use is enabled, remove aws_access_key_id and aws_secret_access_key
           'use_iam_profile' => false
         }
    volumes:
      - "./config:/etc/gitlab:Z"
      - "./logs:/var/log/gitlab:Z"
      - "./data:/var/opt/gitlab:Z"
      - "/etc/localtime:/etc/localtime:ro"
    hostname: git.${DOMAIN}
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.gitlab.rule=Host(`git.${DOMAIN}`)" 
      - "traefik.http.routers.gitlab.entrypoints=websecure" 
      - "traefik.http.routers.gitlab.tls.certresolver=mytlschallenge" 
      - "traefik.http.routers.gitlab.middlewares=gitlab-headers" 
      - "traefik.http.routers.gitlab.service=gitlab" 
      
      - "traefik.http.middlewares.gitlab-headers.headers.customrequestheaders.X_FORWARDED_PROTO=https" 
      - "traefik.http.middlewares.gitlab-headers.headers.customrequestheaders.X_Forwarded-Ssl=on" 
      - "traefik.http.middlewares.gitlab-headers.headers.customresponseheaders.X_FORWARDED_PROTO=https" 
      - "traefik.http.middlewares.gitlab-headers.headers.customresponseheaders.X_Forwarded-Ssl=on" 
      - "traefik.http.services.gitlab.loadbalancer.server.port=80" 

      - "traefik.http.routers.gitlab-registry.rule=Host(`registry.${DOMAIN}`)" 
      - "traefik.http.routers.gitlab-registry.entrypoints=websecure" 
      - "traefik.http.routers.gitlab-registry.tls.certresolver=mytlschallenge" 
      - "traefik.http.routers.gitlab-registry.service=gitlab-registry" 
      - "traefik.http.services.gitlab-registry.loadbalancer.server.port=8500"
    cap_add:
      - SYS_ADMIN
    networks:
      - proxy
  gitlab-runner:
    image: "gitlab/gitlab-runner:latest"
    container_name: "gitlab-runner"
    volumes:
      - "./gitlab-runner/config:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always 
networks:
  proxy:
    external: true

